spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://employeedb.czaoqqcearg8.us-east-1.rds.amazonaws.com/employee
    password: '123456789'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: '5000'

#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    username: Muthu
#    url: jdbc:h2:mem:demo
#    password: '12345'
#  h2:
#    console:
#      enabled: 'true'
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#welcome:
#  message: Spring Boot is Starting....  Welcome to learning!!
#server:
#  port: '8082'

